# Generated by Django 3.2.7 on 2021-09-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210930_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='billing_address',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='checkout_info',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='shipping_address',
            field=models.JSONField(default=dict),
        ),
    ]
