# Generated by Django 3.2.7 on 2021-09-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210930_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
