# Generated by Django 3.2.7 on 2021-09-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_authuser_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
