# Generated by Django 3.2.7 on 2021-09-30 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_authuser_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authuser',
            name='admin',
        ),
    ]
