# Generated by Django 3.2.7 on 2021-09-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_authuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='access_token',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=254, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=254, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='state',
            field=models.CharField(blank=True, max_length=254, verbose_name='state'),
        ),
    ]
