# Generated by Django 3.2.7 on 2021-10-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_authuser_email_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='billing_address',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='checkout_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='shipping_address',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
