# Generated by Django 3.2.7 on 2021-10-18 19:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20211002_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
