# Generated by Django 3.2.7 on 2021-11-19 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_authuser_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Image label'),
        ),
    ]
