# Generated by Django 3.2.7 on 2021-09-28 05:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresponse',
            name='answers',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1000), size=None), blank=True, null=True, size=None),
        ),
    ]
